"""
Professional PDF Report Generator
"""

from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from datetime import datetime
import os

class ReportEngine:
    """Generate professional security reports"""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._add_custom_styles()
    
    def _add_custom_styles(self):
        """Add custom styles for professional reports"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a237e'),
            spaceAfter=30,
            alignment=1
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#0d47a1'),
            spaceAfter=12
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['Normal'],
            fontSize=11,
            textColor=colors.HexColor('#333333'),
            spaceAfter=8
        ))
    
    def generate_security_report(self, data: dict, title: str) -> str:
        """Generate a comprehensive security report"""
        filename = f"reports/{title}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        os.makedirs('reports', exist_ok=True)
        
        doc = SimpleDocTemplate(
            filename,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        content = []
        
        # Title
        content.append(Paragraph("🛡️ Code Orbit Security Toolkit - Security Report", self.styles['CustomTitle']))
        content.append(Spacer(1, 12))
        
        # Date
        content.append(Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}", self.styles['CustomBody']))
        content.append(Spacer(1, 20))
        
        # Security Score
        if 'score' in data:
            content.append(Paragraph(f"Security Score: {data['score']}/100", self.styles['CustomHeading']))
            content.append(Spacer(1, 10))
        
        # Summary Table
        if 'summary' in data:
            content.append(Paragraph("Executive Summary", self.styles['CustomHeading']))
            table_data = [['Metric', 'Value']]
            for key, value in data['summary'].items():
                table_data.append([str(key).replace('_', ' ').title(), str(value)])
            
            table = Table(table_data, colWidths=[3*inch, 3*inch])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0d47a1')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 14),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#e3f2fd')),
                ('TEXTCOLOR', (0, 1), (-1, -1), colors.HexColor('#333333')),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 12),
                ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#bbdefb'))
            ]))
            content.append(table)
            content.append(Spacer(1, 20))
        
        # Vulnerabilities
        if 'vulnerabilities' in data and data['vulnerabilities']:
            content.append(Paragraph("🔍 Vulnerabilities Found", self.styles['CustomHeading']))
            for vuln in data['vulnerabilities']:
                content.append(Paragraph(f"• {vuln.get('type', 'Unknown')}", self.styles['CustomBody']))
                if 'description' in vuln:
                    content.append(Paragraph(f"  {vuln['description']}", self.styles['CustomBody']))
                if 'severity' in vuln:
                    content.append(Paragraph(f"  Severity: {vuln['severity']}", self.styles['CustomBody']))
                content.append(Spacer(1, 6))
        
        # Recommendations
        if 'recommendations' in data:
            content.append(Paragraph("💡 Recommendations", self.styles['CustomHeading']))
            for rec in data['recommendations']:
                content.append(Paragraph(f"• {rec}", self.styles['CustomBody']))
        
        # Footer
        content.append(Spacer(1, 40))
        content.append(Paragraph("---", self.styles['CustomBody']))
        content.append(Paragraph("Generated by Code Orbit Security Toolkit", self.styles['CustomBody']))
        content.append(Paragraph("Developed by Pradheepa. M | Code Orbit Tech Internship", self.styles['CustomBody']))
        
        # Build PDF
        doc.build(content)
        return filename